In [1]:
import pandas as pd
import requests

In [10]:
standings_url = "https://fbref.com/en/comps/9/2022-2023/2022-2023-Premier-League-Stats"  #2022-23 season
data = requests.get(standings_url)

In [11]:
data

In [12]:
from bs4 import BeautifulSoup

In [13]:
soup = BeautifulSoup(data.text)

In [14]:
standings_table = soup.select('table.stats_table')[0]   #css selector - classtype.name

In [15]:
links = standings_table.find_all('a')  #finds all tags with 'a' type

In [16]:
links = [l.get("href") for l in links]

In [17]:
links = [l for l in links if "/squads/" in l]

In [18]:
team_urls = [f"https://fbref.com/{l}" for l in links]

In [19]:
team_urls

['https://fbref.com//en/squads/b8fd03ef/2022-2023/Manchester-City-Stats',
 'https://fbref.com//en/squads/18bb7c10/2022-2023/Arsenal-Stats',
 'https://fbref.com//en/squads/19538871/2022-2023/Manchester-United-Stats',
 'https://fbref.com//en/squads/b2b47a98/2022-2023/Newcastle-United-Stats',
 'https://fbref.com//en/squads/822bd0ba/2022-2023/Liverpool-Stats',
 'https://fbref.com//en/squads/d07537b9/2022-2023/Brighton-and-Hove-Albion-Stats',
 'https://fbref.com//en/squads/8602292d/2022-2023/Aston-Villa-Stats',
 'https://fbref.com//en/squads/361ca564/2022-2023/Tottenham-Hotspur-Stats',
 'https://fbref.com//en/squads/cd051869/2022-2023/Brentford-Stats',
 'https://fbref.com//en/squads/fd962109/2022-2023/Fulham-Stats',
 'https://fbref.com//en/squads/47c64c55/2022-2023/Crystal-Palace-Stats',
 'https://fbref.com//en/squads/cff3d9bb/2022-2023/Chelsea-Stats',
 'https://fbref.com//en/squads/8cec06e1/2022-2023/Wolverhampton-Wanderers-Stats',
 'https://fbref.com//en/squads/7c21e445/2022-2023/West-Ham-United-Stats',
 'https://fbref.com//en/squads/4ba7cbea/2022-2023/Bournemouth-Stats',
 'https://fbref.com//en/squads/e4a775cb/2022-2023/Nottingham-Forest-Stats',
 'https://fbref.com//en/squads/d3fd31cc/2022-2023/Everton-Stats',
 'https://fbref.com//en/squads/a2d435b3/2022-2023/Leicester-City-Stats',
 'https://fbref.com//en/squads/5bfb9659/2022-2023/Leeds-United-Stats',
 'https://fbref.com//en/squads/33c895d4/2022-2023/Southampton-Stats']

In [20]:
team_url = team_urls[0]

In [21]:
team_url

'https://fbref.com//en/squads/b8fd03ef/2022-2023/Manchester-City-Stats'

In [22]:
data = requests.get(team_url)

In [23]:
matches = pd.read_html(data.text, match = 'Scores & Fixtures' )

In [24]:
matches[0].head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,xG,xGA,Poss,Attendance,Captain,Formation,Opp Formation,Referee,Match Report,Notes
0,2022-07-30,17:00,Community Shield,FA Community Shield,Sat,Neutral,L,1,3,Liverpool,NaN,NaN,57,NaN,Rúben Dias,4-3-3,4-3-3,Craig Pawson,Match Report,NaN
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2,0,West Ham,2.2,0.5,75,62443.0,İlkay Gündoğan,4-3-3,4-2-3-1,Michael Oliver,Match Report,NaN
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,1.7,0.1,67,53453.0,İlkay Gündoğan,4-2-3-1,3-4-3,David Coote,Match Report,NaN
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,2.1,1.8,69,52258.0,İlkay Gündoğan,4-3-3,4-3-3,Jarred Gillett,Match Report,NaN
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,2.2,0.1,74,53112.0,Kevin De Bruyne,4-2-3-1,5-4-1,Darren England,Match Report,NaN

In [26]:
soup = BeautifulSoup(data.text)

In [27]:
links = soup.find_all('a')

In [28]:
links = [l.get("href") for l in links]

In [29]:
links = [l for l in links if l and "/all_comps/shooting/" in l]

In [30]:
links

['/en/squads/b8fd03ef/2022-2023/matchlogs/all_comps/shooting/Manchester-City-Match-Logs-All-Competitions',
 '/en/squads/b8fd03ef/2022-2023/matchlogs/all_comps/shooting/Manchester-City-Match-Logs-All-Competitions',
 '/en/squads/b8fd03ef/2022-2023/matchlogs/all_comps/shooting/Manchester-City-Match-Logs-All-Competitions',
 '/en/squads/b8fd03ef/2022-2023/matchlogs/all_comps/shooting/Manchester-City-Match-Logs-All-Competitions']

In [31]:
data = requests.get(f"https://fbref.com/{links[0]}").text

In [32]:
shooting = pd.read_html(data, match  = "Shooting")[0]

In [33]:
shooting.head()

  For Manchester City                                                     \
                 Date   Time              Comp                Round  Day
0          2022-07-30  17:00  Community Shield  FA Community Shield  Sat
1          2022-08-07  16:30    Premier League          Matchweek 1  Sun
2          2022-08-13  15:00    Premier League          Matchweek 2  Sat
3          2022-08-21  16:30    Premier League          Matchweek 3  Sun
4          2022-08-27  15:00    Premier League          Matchweek 4  Sat

                                             ... Standard                \
     Venue Result   GF   GA        Opponent  ...     Dist   FK PK PKatt
0  Neutral      L  1.0  3.0       Liverpool  ...      NaN  NaN  0     0
1     Away      W  2.0  0.0        West Ham  ...     18.7  1.0  1     1
2     Home      W  4.0  0.0     Bournemouth  ...     17.5  0.0  0     0
3     Away      D  3.0  3.0   Newcastle Utd  ...     16.2  1.0  0     0
4     Home      W  4.0  2.0  Crystal Palace  ...     14.1  0.0  0     0

  Expected                           Unnamed: 25_level_0
        xG npxG npxG/Sh G-xG np:G-xG        Match Report
0      NaN  NaN     NaN  NaN     NaN        Match Report
1      2.2  1.4    0.11 -0.2    -0.4        Match Report
2      1.7  1.7    0.09  1.3     1.3        Match Report
3      2.1  2.1    0.10  0.9     0.9        Match Report
4      2.2  2.2    0.13  1.8     1.8        Match Report

[5 rows x 26 columns]

In [34]:
shooting.columns = shooting.columns.droplevel()  #dropped multilevel index

In [35]:
shooting.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Match Report
0,2022-07-30,17:00,Community Shield,FA Community Shield,Sat,Neutral,L,1.0,3.0,Liverpool,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Match Report
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,West Ham,...,18.7,1.0,1,1,2.2,1.4,0.11,-0.2,-0.4,Match Report
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,Bournemouth,...,17.5,0.0,0,0,1.7,1.7,0.09,1.3,1.3,Match Report
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,Newcastle Utd,...,16.2,1.0,0,0,2.1,2.1,0.10,0.9,0.9,Match Report
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,...,14.1,0.0,0,0,2.2,2.2,0.13,1.8,1.8,Match Report

In [36]:
shooting.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          61 non-null     object
 1   Time          61 non-null     object
 2   Comp          61 non-null     object
 3   Round         61 non-null     object
 4   Day           61 non-null     object
 5   Venue         61 non-null     object
 6   Result        62 non-null     object
 7   GF            61 non-null     float64
 8   GA            61 non-null     float64
 9   Opponent      61 non-null     object
 10  Gls           62 non-null     int64
 11  Sh            62 non-null     int64
 12  SoT           62 non-null     int64
 13  SoT%          62 non-null     float64
 14  G/Sh          62 non-null     float64
 15  G/SoT         61 non-null     float64
 16  Dist          52 non-null     float64
 17  FK            52 non-null     float64
 18  PK            62 non-null     int64
 19  PKatt         62 non-null     int64
 20  xG            51 non-null     float64
 21  npxG          51 non-null     float64
 22  npxG/Sh       52 non-null     float64
 23  G-xG          52 non-null     float64
 24  np:G-xG       52 non-null     float64
 25  Match Report  61 non-null     object
dtypes: float64(12), int64(5), object(9)
memory usage: 12.7+ KB

In [37]:
team_data = matches[0].merge(shooting[["Date", "Sh", "SoT", "Dist", "FK", "PK", "PKatt"]], on = "Date" )

In [38]:
team_data.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Opp Formation,Referee,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt
0,2022-07-30,17:00,Community Shield,FA Community Shield,Sat,Neutral,L,1,3,Liverpool,...,4-3-3,Craig Pawson,Match Report,NaN,14,8,NaN,NaN,0,0
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2,0,West Ham,...,4-2-3-1,Michael Oliver,Match Report,NaN,13,1,18.7,1.0,1,1
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,...,3-4-3,David Coote,Match Report,NaN,19,7,17.5,0.0,0,0
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,...,4-3-3,Jarred Gillett,Match Report,NaN,21,10,16.2,1.0,0,0
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,5-4-1,Darren England,Match Report,NaN,18,5,14.1,0.0,0,0

In [39]:
team_data.shape

(61, 26)

In [40]:
team_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 61 entries, 0 to 60
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           61 non-null     object
 1   Time           61 non-null     object
 2   Comp           61 non-null     object
 3   Round          61 non-null     object
 4   Day            61 non-null     object
 5   Venue          61 non-null     object
 6   Result         61 non-null     object
 7   GF             61 non-null     int64
 8   GA             61 non-null     int64
 9   Opponent       61 non-null     object
 10  xG             51 non-null     float64
 11  xGA            51 non-null     float64
 12  Poss           61 non-null     int64
 13  Attendance     60 non-null     float64
 14  Captain        61 non-null     object
 15  Formation      61 non-null     object
 16  Opp Formation  61 non-null     object
 17  Referee        61 non-null     object
 18  Match Report   61 non-null     object
 19  Notes          6 non-null      object
 20  Sh             61 non-null     int64
 21  SoT            61 non-null     int64
 22  Dist           51 non-null     float64
 23  FK             51 non-null     float64
 24  PK             61 non-null     int64
 25  PKatt          61 non-null     int64
dtypes: float64(5), int64(7), object(14)
memory usage: 12.9+ KB

In [41]:
years = list(range(2023, 2020, -1))  #2023 to 2021 (3 years)
all_matches = []

In [42]:
standings_url = "https://fbref.com/en/comps/9/2023-2024/2023-2024-Premier-League-Stats" #2023-24 season

In [43]:
import time
for year in years:
    data = requests.get(standings_url)
    soup = BeautifulSoup(data.text)
    standings_table = soup.select('table.stats_table')[0]

    links = [l.get("href") for l in standings_table.find_all('a')]
    links = [l for l in links if '/squads/' in l]
    team_urls = [f"https://fbref.com{l}" for l in links]
    
    previous_season = soup.select("a.prev")[0].get("href")
    standings_url = f"https://fbref.com{previous_season}"
    
    for team_url in team_urls:
        team_name = team_url.split("/")[-1].replace("-Stats", "").replace("-", " ")
        data = requests.get(team_url)
        matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
        soup = BeautifulSoup(data.text)
        links = [l.get("href") for l in soup.find_all('a')]
        links = [l for l in links if l and 'all_comps/shooting/' in l]
        data = requests.get(f"https://fbref.com{links[0]}")
        shooting = pd.read_html(data.text, match="Shooting")[0]
        shooting.columns = shooting.columns.droplevel()
        try:
            team_data = matches.merge(shooting[["Date", "Sh", "SoT", "Dist", "FK", "PK", "PKatt"]], on="Date")
        except ValueError:
            continue
        team_data = team_data[team_data["Comp"] == "Premier League"]
        
        team_data["Season"] = year
        team_data["Team"] = team_name
        all_matches.append(team_data)
        time.sleep(15)

In [44]:
len(all_matches)

60

In [84]:
match_df = pd.concat(all_matches)

In [85]:
match_df.columns = [c.lower() for c in match_df.columns]

In [86]:
match_df.reset_index(drop=True,inplace=True)

In [96]:
match_df = match_df.drop(columns=['notes','match report'])  #removed empty columns

In [97]:
match_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2280 entries, 0 to 2279
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           2280 non-null   object
 1   time           2280 non-null   object
 2   comp           2280 non-null   object
 3   round          2280 non-null   object
 4   day            2280 non-null   object
 5   venue          2280 non-null   object
 6   result         2280 non-null   object
 7   gf             2280 non-null   object
 8   ga             2280 non-null   object
 9   opponent       2280 non-null   object
 10  xg             2280 non-null   float64
 11  xga            2280 non-null   float64
 12  poss           2280 non-null   float64
 13  attendance     2278 non-null   float64
 14  captain        2280 non-null   object
 15  formation      2280 non-null   object
 16  opp formation  2280 non-null   object
 17  referee        2280 non-null   object
 18  sh             2280 non-null   float64
 19  sot            2280 non-null   float64
 20  dist           2280 non-null   float64
 21  fk             2280 non-null   float64
 22  pk             2280 non-null   int64
 23  pkatt          2280 non-null   int64
 24  season         2280 non-null   int64
 25  team           2280 non-null   object
dtypes: float64(8), int64(3), object(15)
memory usage: 463.2+ KB

In [98]:
match_df

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,opp formation,referee,sh,sot,dist,fk,pk,pkatt,season,team
0,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,5-4-1,Craig Pawson,17.0,8.0,13.9,0.0,0,0,2023,Manchester City
1,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,4-3-3,Robert Jones,14.0,4.0,17.9,0.0,0,0,2023,Manchester City
2,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,3-5-2,Jarred Gillett,29.0,9.0,17.3,2.0,0,1,2023,Manchester City
3,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,4-3-3,Michael Oliver,6.0,4.0,14.8,0.0,1,1,2023,Manchester City
4,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,3,1,West Ham,...,4-2-3-1,Andy Madley,29.0,13.0,16.4,1.0,0,0,2023,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Away,L,0,2,Aston Villa,...,4-1-4-1,John Brooks,9.0,3.0,21.6,0.0,0,0,2021,Norwich City
2276,2022-05-08,14:00,Premier League,Matchweek 36,Sun,Home,L,0,4,West Ham,...,4-2-3-1,Robert Jones,8.0,2.0,22.2,1.0,0,0,2021,Norwich City
2277,2022-05-11,19:45,Premier League,Matchweek 21,Wed,Away,L,0,3,Leicester City,...,4-2-3-1,Simon Hooper,9.0,5.0,17.0,0.0,0,0,2021,Norwich City
2278,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,1,1,Wolves,...,3-4-3,Tony Harrington,11.0,2.0,14.4,0.0,0,0,2021,Norwich City
2279,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,L,0,5,Tottenham,...,3-4-3,Chris Kavanagh,9.0,0.0,18.6,0.0,0,0,2021,Norwich City

In [100]:
match_df.to_csv("matches.csv")